// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'order_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

OrderData _$OrderDataFromJson(Map<String, dynamic> json) => OrderData(
      uuid: json['uuid'] as String?,
      orderCouponDiscount: (json['order_coupon_discount'] as num?)?.toDouble(),
      orderSubTotal: (json['order_sub_total'] as num?)?.toDouble(),
      orderShipping: (json['order_shipping'] as num?)?.toDouble(),
      orderFinalAmount: (json['order_final_amount'] as num?)?.toDouble(),
      currencyId: json['currency_id'] as int?,
      vat: (json['vat'] as num?)?.toDouble(),
      walletUsed: json['wallet_used'] as int?,
      exchangeRate: (json['exchange_rate'] as num?)?.toDouble(),
      couponId: json['coupon_id'] as int?,
      rulePropertyId: json['rule_property_id'] as int?,
      paymentMethod: json['payment_method'] as String?,
      customerId: json['customer_id'],
      billingFirstName: json['billing_first_name'] as String?,
      billingLastName: json['billing_last_name'] as String?,
      billingCountry: json['billing_country'] as String?,
      billingStreetName: json['billing_street_name'] as String?,
      billingApartmentDetails: json['billing_apartment_details'] as String?,
      buildingNo: json['building_no'] as String?,
      buildingName: json['building_name'] as String?,
      buildingLocation: json['building_location'] as String?,
      buildingEmirate: json['building_emirate'] as String?,
      billingPincode: json['billing_pincode'] as String?,
      billingTownCity: json['billing_town_city'] as String?,
      billingEmailId: json['billing_email_id'] as String?,
      billingPhone: json['billing_phone'] as String?,
      billingOrderNotes: json['billing_order_notes'] as String?,
      createdIp: json['created_ip'] as String?,
      invoiceId: json['invoice_id'] as String?,
      secretKey: json['secret_key'] as String?,
      createdAt: json['created_at'] as String?,
      createdTime: json['created_time'] as String?,
      updatedAt: json['updated_at'] as String?,
      orderId: json['order_id'] as int?,
    )..orderTime = json['order_time'] as String?;

Map<String, dynamic> _$OrderDataToJson(OrderData instance) => <String, dynamic>{
      'uuid': instance.uuid,
      'order_coupon_discount': instance.orderCouponDiscount,
      'order_sub_total': instance.orderSubTotal,
      'order_shipping': instance.orderShipping,
      'order_final_amount': instance.orderFinalAmount,
      'currency_id': instance.currencyId,
      'vat': instance.vat,
      'wallet_used': instance.walletUsed,
      'exchange_rate': instance.exchangeRate,
      'coupon_id': instance.couponId,
      'rule_property_id': instance.rulePropertyId,
      'payment_method': instance.paymentMethod,
      'customer_id': instance.customerId,
      'billing_first_name': instance.billingFirstName,
      'billing_last_name': instance.billingLastName,
      'billing_country': instance.billingCountry,
      'billing_street_name': instance.billingStreetName,
      'billing_apartment_details': instance.billingApartmentDetails,
      'building_no': instance.buildingNo,
      'building_name': instance.buildingName,
      'building_location': instance.buildingLocation,
      'building_emirate': instance.buildingEmirate,
      'billing_pincode': instance.billingPincode,
      'billing_town_city': instance.billingTownCity,
      'billing_email_id': instance.billingEmailId,
      'billing_phone': instance.billingPhone,
      'billing_order_notes': instance.billingOrderNotes,
      'created_ip': instance.createdIp,
      'invoice_id': instance.invoiceId,
      'secret_key': instance.secretKey,
      'created_at': instance.createdAt,
      'created_time': instance.createdTime,
      'updated_at': instance.updatedAt,
      'order_id': instance.orderId,
      'order_time': instance.orderTime,
    };
